version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: api-monitor-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: api_monitor
      POSTGRES_PASSWORD: api_monitor_password
      POSTGRES_DB: api_monitor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: